# Generated by Django 6.1.1 on 2026-09-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='speices',
            new_name='species',
        ),
    ]
